services:
  app:
    image: ghcr.io/mtahatari19/gh-new-actions:${TAG:-latest}
    container_name: gh-new-actions
    restart: unless-stopped
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 15s
      timeout: 5s
      retries: 5
