name: Deployment Exercise 1
on: push

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM, raspberrypi]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'npm'

      - name: Print Node & NPM versions
        run: |
          which node
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          node -v
          npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploying..."
