name: Handle issues
on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  notify-telegram:
    runs-on: [self-hosted, Linux, ARM, raspberrypi]
    steps:
      - name: Output event details
        run: |
          echo "::group::github.event"
          echo '${{ toJson(github.event) }}'
          echo "::endgroup::"

      - name: Build message
        id: msg
        shell: bash
        run: |
          set -euo pipefail

          TITLE="${{ github.event.issue.title }}"
          URL="${{ github.event.issue.html_url }}"
          ACTION="${{ github.event.action }}"
          REPO="${{ github.repository }}"
          SENDER="${{ github.actor }}"
          LABEL="${{ github.event.label.name || '' }}"

          TEXT=$(cat <<EOF
          📬 *$ACTION* in *$REPO*
          • *Title:* $TITLE
          $( [ -n "$LABEL" ] && echo "• *Label:* $LABEL" )
          • *By:* $SENDER
          🔗 $URL
          EOF
          )

          {
            echo "text<<EOF"
            echo "$TEXT"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Send to Telegram (action)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: ${{ steps.msg.outputs.text }}
