name: Handle issues
on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "::group::github.event"
          echo '${{ toJson(github.event) }}'
          echo "::endgroup::"

      - name: Build message
        id: msg
        shell: bash
        run: |
          TITLE="${{ github.event.issue.title }}"
          URL="${{ github.event.issue.html_url }}"
          ACTION="${{ github.event.action }}"
          REPO="${{ github.repository }}"
          SENDER="${{ github.actor }}"
          LABEL="${{ github.event.label.name || '' }}"

          TEXT="📬 *$ACTION* in *$REPO*\"
          TEXT+="• *Title:* $TITLE\"
          if [ -n "$LABEL" ]; then TEXT+="• *Label:* $LABEL\"; fi
          TEXT+="• *By:* $SENDER\"
          TEXT+="🔗 $URL"

          {
            echo "text<<EOF"
            echo "$TEXT"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Send to Telegram (action)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: ${{ steps.msg.outputs.text }}
