name: Handle issues
on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled

jobs:
  notify-telegram:
    runs-on: [self-hosted, Linux, ARM, raspberrypi]
    steps:
      - name: Send to Telegram
        shell: bash
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -euo pipefail

          TITLE="${{ github.event.issue.title }}"
          URL="${{ github.event.issue.html_url }}"
          ACTION="${{ github.event.action }}"
          REPO="${{ github.repository }}"
          SENDER="${{ github.actor }}"
          LABEL="${{ github.event.label.name || '' }}"

          TEXT=$(printf '%s\n%s\n%s\n%s\n%s\n%s\n' \
            "Issue event" \
            "Action: ${ACTION}" \
            "Repo: ${REPO}" \
            "Title: ${TITLE}" \
            "Label: ${LABEL}" \
            "URL: ${URL}")

          API="https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage"
          curl -fsS -X POST "$API" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            --data-urlencode "text=${TEXT}"
